//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmosMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albums
    {
        public Albums()
        {
            this.Song = new HashSet<Song>();
        }
    
        public System.Guid album_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> add_date { get; set; }
        public Nullable<int> rating { get; set; }
        public string cover { get; set; }
        public System.Guid user_id { get; set; }
        public Nullable<int> year { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Song> Song { get; set; }
    }
}
