//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmosMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public System.Guid history_id { get; set; }
        public System.DateTime listening_time { get; set; }
        public System.Guid user_id { get; set; }
        public System.Guid song_id { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Song Song { get; set; }
    }
}
